# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Merkulov Maksim
tagline:          'Merkulov Maksim'
description:      'My work.<br>My interests in this blog'
url:              http://lepotuli.ru/merkulov/

author:
  name:           'Merkulov Maksim'
  url:            http://lepotuli.ru/merkulov/

paginate:         2
# google_analytics: 'UA-91425204-3'
# bing_seo:     'ECA8D4503D79297E7BB223666F18CAF8'
# emailme:          mailto:lqian8@jhu.edu

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/DomenZero/merkulov.git

# tags:

# github_username:  qian256
# facebook_username: joe.qian
# linkedin_username: long-qian